# 我們會利用的資料夾
# 其實也不用寫下來 (這些都是預設值)
contentDir: content
staticDir: static
layoutDir: layouts
publishDir: public
staticDir: static

# 有些東西需要這個選項才會支援中文的樣子
hasCJKLanguage: true

# 我會用README檔來解釋各個資料夾的意義，但我們不希望這些檔案被輸出。
ignoreFiles:
  - README\.md$
  - readme\.md$

# 有些Hugo模板語言的函數需要這個才能產生正確的連結
baseURL: https://nkust-dcc.github.io

sitename: 高科大夢想漫研社
description: |
  哈囉，這裡是夢想漫研☆
  想與人分享動漫心得與快樂
  卻找不到同好嗎？
  想增進漫畫技巧
  卻苦無老師指導嗎?
  沒關係!!
  這裡讓你兩個願望一次滿足!!
